server:
  port: 7000
spring:
  cloud:
    gateway:
      routes:
        - id: service-flights
          #lb:// cuando se va a acceder a través de Eureka
          uri: lb://servicio-flights #http://localhost:9000
          predicates:
            - Path=/sflights/**
          filters:
            - RewritePath=/sflights/*, /

        - id: service-hotels
          #lb:// cuando se va a acceder a través de Eureka
          uri: lb://servicio-hoteles #http://localhost:8000
          predicates:
            - Path=/shotels/**
          filters:
            - RewritePath=/shotels/*, /

        - id: service-bookings
          #lb:// cuando se va a acceder a través de Eureka
          uri: lb://servicio-bookings #http://localhost:10000
          predicates:
            - Path=/sbooking/**
          filters:
            - RewritePath=/sbooking/*, /
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
